sudo: false
os: linux
dist: trusty
language: php

php:
- 7.0
- 7.1
- 7.2
- nightly

matrix:
  allow_failures:
  - php: nightly

branches:
  only:
  - master
  - /^\d+\.x$/
  - /^\d+\.\d+$/
  - /^\d+\.\d+\.\d+$/

script:
- exit 0
